### ISSUE TITLE
Error when try to run supervised/semi supervised experiment

### ISSUE THREAD

**Issue by wandakinasih** [haryoa/stif-indonesia#11]
Hi!

I found error when trying to run supervised/semi supervised experiment `TypeError: __init__() got an unexpected keyword argument 'capture_output'`

<img width="1164" alt="Screen Shot 2020-11-24 at 13 47 27" src="https://user-images.githubusercontent.com/29034663/100058528-0757de00-2e5c-11eb-8049-7070a7d97b2d.png">

Python 3.6.7
Linux 4.14.138+ x86_64

**Comment by haryoa** [comment]
Based on the stackoverflow answer, Python 3.6 does not support the `capture_output` argument in subprocess package. 
https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196

Use a newer version of Python (in our documentation, we test our system on Python 3.9)
