### ISSUE TITLE
Error when try to run supervised/semi supervised experiment (mac version)

### ISSUE THREAD

**Issue by wandakinasih** [haryoa/stif-indonesia#12]
So i have download moses for mac, but it seems that there are some incomplete dependency to `xmlrpc-c`

<img width="740" alt="Screen Shot 2020-11-24 at 13 56 39" src="https://user-images.githubusercontent.com/29034663/100059487-be088e00-2e5d-11eb-8067-49d12fd310ce.png">

Python 3.7.7

**Comment by haryoa** [comment]
Hello, 

This is a duplicate from issue #6 ( The OP also mentioned it)

We didn't test our source code on mac. The error might be caused by the compiled binary file provided by the author of the Moses Toolkit.

Sorry for the inconvenience

**Comment by Picasso1503** [comment]
I have the same problem when I runned it from WSL2 (Windows Subsystem for Linux 2)

![Screenshot (9)](https://user-images.githubusercontent.com/73958120/101792576-6f364600-3b37-11eb-91f5-79176072c9a1.png)

**Comment by haryoa** [comment]
Hello @Picasso1503,

Could you run this script on your `stif-indonesia` folder and paste the error here?

```bash
nice moses/moses/scripts/training/train-model.perl -root-dir output/supervised/train -corpus data/labelled/train -f inf -e for -alignment grow-diag-final-and                         -reordering msd-bidirectional-fe                         -lm 0:3:[ABSOLUTE_PATH_TO_STIF_INDONESIA]/stif-indonesia/output/supervised/lm/blm/data.blm.for -core 2 -external-bin-dir moses/training-tools --mgiza
```
Change the `[ABSOLUTE_PATH_TO_STIF_INDONESIA]` with the absolute path of stif-indonesia folder (use `pwd`).

The error on MAC and WSL2 is different. 
The error in MAC may be caused by `xmlrpc` but in WSL2, the error is different (you can run KEN-LM).

**Comment by Picasso1503** [comment]
Thankyou. This is what I've got

**Comment by Picasso1503** [comment]
Thankyou. This what I've got
![Uploading Capture.PNG…]()

**Comment by Picasso1503** [comment]
and what do you mean about change the path to absolute path? I dont understand yet

**Comment by haryoa** [comment]
Absolute path means the path file from your root directory to your file or directory in your OS.
For example:
`/home/muhammadrizky15/stif-indonesia/`

use `pwd` command in your WSL2 terminal to see the absolute path of the folder `stif-indonesia`

I cannot see your Capture.PNG. Would you mind to edit it? Thank you.

**Comment by Picasso1503** [comment]
This what I've got
![Capture](https://user-images.githubusercontent.com/73958120/101976970-d9a4ce80-3c7c-11eb-82f5-693bb2d60b64.PNG)

**Comment by Picasso1503** [comment]
![Capture 2](https://user-images.githubusercontent.com/73958120/101977319-6781b900-3c7f-11eb-9bf1-432e9aa0c4e0.PNG)

**Comment by haryoa** [comment]
change `[ABSOLUTE_PATH_TO_STIF_INDONESIA]/stif-indonesia/output/supervised/lm/blm/data.blm.for` to `/home/muhammadrizky15/stif-indonesia/stif-indonesia/output/supervised/lm/blm/data.blm.for` in your -lm arguments. That `/mnt/d/` path is for my local computer...

**Comment by Picasso1503** [comment]
> change `[ABSOLUTE_PATH_TO_STIF_INDONESIA]/stif-indonesia/output/supervised/lm/blm/data.blm.for` to `/home/muhammadrizky15/stif-indonesia/stif-indonesia/output/supervised/lm/blm/data.blm.for` in your -lm arguments. That `/mnt/d/` path is for my local computer...

I don't understand, can u explain about the command line, bcs I never used linux system before

**Comment by haryoa** [comment]
```bash
nice moses/moses/scripts/training/train-model.perl -root-dir output/supervised/train -corpus data/labelled/train -f inf -e for -alignment grow-diag-final-and                         -reordering msd-bidirectional-fe                         -lm 0:3:/home/muhammadrizky15/stif-indonesia/stif-indonesia/output/supervised/lm/blm/data.blm.for -core 2 -external-bin-dir moses/training-tools --mgiza
```

Here you go

**Comment by haryoa** [comment]
```bash
nice moses/moses/scripts/training/train-model.perl -root-dir output/supervised/train -corpus data/labelled/train -f inf -e for -alignment grow-diag-final-and                         -reordering msd-bidirectional-fe                         -lm 0:3:/home/muhammadrizky15/stif-indonesia/output/supervised/lm/blm/data.blm.for -core 2 -external-bin-dir moses/training-tools --mgiza
```

Here you go

**Comment by Picasso1503** [comment]
I've got error 
![33](https://user-images.githubusercontent.com/73958120/102442739-a5a02380-4057-11eb-8577-c0f5de1082f4.PNG)

is it important to install miniconda? but I've been installed python environment to WSL2

**Comment by haryoa** [comment]
As long as you have Python 3.7++ on your WSL2, it is good to go. You do not need to install miniconda.

Can you do these steps in a sequence:
1. `rm -rf output` (remove output folder)
2. `python -m stif_indonesia --exp-scenario supervised` (run supervised experiment that will output the error)
3. `nice moses/moses/scripts/training/train-model.perl -root-dir output/supervised/train -corpus data/labelled/train -f inf -e for -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:/home/roggl552vw/stif-indonesia/output/supervised/lm/blm/data.blm.for -core 2 -external-bin-dir moses/training-tools --mgiza` (run training)
4. Screenshot your error here

Note the `roggl552vw` on the step 3. I use your username on your WSL2. If you use different username, you need to change that part.

**Comment by Picasso1503** [comment]
![1](https://user-images.githubusercontent.com/73958120/102516067-0a439880-40c1-11eb-801f-5829712e047d.PNG)
First, delete output folder.

![2](https://user-images.githubusercontent.com/73958120/102516082-0e6fb600-40c1-11eb-8d73-75a6f1654f8d.PNG)
The second command line, I've got this error

![3](https://user-images.githubusercontent.com/73958120/102516087-116aa680-40c1-11eb-9ed1-d0b8321a9c13.PNG)
The third command line, I've got this error as the same as before

**Comment by haryoa** [comment]
I think the error is caused when the program do training process. It didn't output `extract.o.sorted.gz` on your folder. 
I think, I need your full log to inspect your error.

Before you do the following, are you sure you download the right moses by running this command `bash scripts/download_moses.sh` ?

I can run it perfectly with my WSL2 on WSL2 Ubuntu 20.04 (I think if you have Ubuntu 17.04++, it can work).

Do these:
1. `rm -rf output` (remove output folder)
2. `python -m stif_indonesia --exp-scenario supervised` (run supervised experiment that will output the error)
3. `sudo nice moses/moses/scripts/training/train-model.perl -root-dir output/supervised/train -corpus data/labelled/train -f inf -e for -alignment grow-diag-final-and -reordering msd-bidirectional-fe -lm 0:3:/home/roggl552vw/stif-indonesia/output/supervised/lm/blm/data.blm.for -core 2 -external-bin-dir moses/training-tools --mgiza &> out.log` (run training and redirect the output to out.log. I add sudo here because I suspect that you didn't give permission to write to the folder.)
4. upload out.log here.

Also I need you to screen shot your `ls -al ls -al output/supervised/train/model` after you do these steps.

**Comment by Picasso1503** [comment]
![4](https://user-images.githubusercontent.com/73958120/102648662-77772c80-419a-11eb-8e82-7a0d6abac149.PNG)

[out.log](https://github.com/haryoa/stif-indonesia/files/5717495/out.log)

That's All

**Comment by Picasso1503** [comment]
Ya, I've double check, I runned bash scripts/download_moses.sh in stif-indonesia folder

**Comment by goFrendiAsgard** [comment]
> ![1](https://user-images.githubusercontent.com/73958120/102516067-0a439880-40c1-11eb-801f-5829712e047d.PNG)
> First, delete output folder.
> 
> ![2](https://user-images.githubusercontent.com/73958120/102516082-0e6fb600-40c1-11eb-8d73-75a6f1654f8d.PNG)
> The second command line, I've got this error
> 
> ![3](https://user-images.githubusercontent.com/73958120/102516087-116aa680-40c1-11eb-9ed1-d0b8321a9c13.PNG)
> The third command line, I've got this error as the same as before

Hello @Picasso1503 , have you try to delete `output` directory and retrain?

**Comment by Picasso1503** [comment]
> > ![1](https://user-images.githubusercontent.com/73958120/102516067-0a439880-40c1-11eb-801f-5829712e047d.PNG)
> > First, delete output folder.
> > ![2](https://user-images.githubusercontent.com/73958120/102516082-0e6fb600-40c1-11eb-8d73-75a6f1654f8d.PNG)
> > The second command line, I've got this error
> > ![3](https://user-images.githubusercontent.com/73958120/102516087-116aa680-40c1-11eb-9ed1-d0b8321a9c13.PNG)
> > The third command line, I've got this error as the same as before
> 
> Hello @Picasso1503 , have you try to delete `output` directory and retrain?

Yap @goFrendiAsgard , I've been removed it using rm -rf output
