### ISSUE TITLE
Informal-Formal Dictionary

### ISSUE THREAD

**Issue by rzsgrt** [haryoa/stif-indonesia#13]
Hi, saya sangat tertarik dengan paper yang anda buat. 
Dari tabel 6, score BLEU metode dictionary berada tidak jauh dengan score metode PBSMT dan pretrain GPT. Sayangnya, link github untuk dictionary yg digunakan tidak dapat diakses. Apakah dictionary ini penggunaannya terbatas?

Terima kasih

**Comment by haryoa** [comment]
Dictionary tersebut dihapus pada repository pemiliknya. Pada saat kami meriset ini, kami masih memiliki aksesnya.

Anda bisa coba menggantinya dengan dictionary yang kami link pada Readme.md di home.

Cheers!

**Comment by rezasugiarto** [comment]
Hi, apakah anda dapat membagikan dictionary yg anda gunakan?

**Comment by rzsgrt** [comment]
Hi, terima kasih infonya. Have a nice day!
